package grammar.Absyn; // Java Package generated by the BNF Converter.

public class ActionStatement extends StatementRule {
  public final ExportStatementRule exportstatementrule_;
  public ActionStatement(ExportStatementRule p1) { exportstatementrule_ = p1; }

  public <R,A> R accept(grammar.Absyn.StatementRule.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.ActionStatement) {
      grammar.Absyn.ActionStatement x = (grammar.Absyn.ActionStatement)o;
      return this.exportstatementrule_.equals(x.exportstatementrule_);
    }
    return false;
  }

  public int hashCode() {
    return this.exportstatementrule_.hashCode();
  }


}
