package grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class CheckingStatementRule implements java.io.Serializable {
  public abstract <R,A> R accept(CheckingStatementRule.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammar.Absyn.EmptyChecking p, A arg);
    public R visit(grammar.Absyn.UniversalChecking p, A arg);
    public R visit(grammar.Absyn.SubsetChecking p, A arg);

  }

}
