package grammar.Absyn; // Java Package generated by the BNF Converter.

public class CheckingStatement extends StatementRule {
  public final CheckingStatementRule checkingstatementrule_;
  public CheckingStatement(CheckingStatementRule p1) { checkingstatementrule_ = p1; }

  public <R,A> R accept(grammar.Absyn.StatementRule.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.CheckingStatement) {
      grammar.Absyn.CheckingStatement x = (grammar.Absyn.CheckingStatement)o;
      return this.checkingstatementrule_.equals(x.checkingstatementrule_);
    }
    return false;
  }

  public int hashCode() {
    return this.checkingstatementrule_.hashCode();
  }


}
