package grammar.Absyn; // Java Package generated by the BNF Converter.

public class ExportTextStatement extends ExportStatementRule {
  public final AutomataExpressionRule automataexpressionrule_;
  public ExportTextStatement(AutomataExpressionRule p1) { automataexpressionrule_ = p1; }

  public <R,A> R accept(grammar.Absyn.ExportStatementRule.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.ExportTextStatement) {
      grammar.Absyn.ExportTextStatement x = (grammar.Absyn.ExportTextStatement)o;
      return this.automataexpressionrule_.equals(x.automataexpressionrule_);
    }
    return false;
  }

  public int hashCode() {
    return this.automataexpressionrule_.hashCode();
  }


}
