package grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class ExportStatementRule implements java.io.Serializable {
  public abstract <R,A> R accept(ExportStatementRule.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammar.Absyn.ExportDotStatement p, A arg);
    public R visit(grammar.Absyn.ExportTextStatement p, A arg);

  }

}
