package grammar.Absyn; // Java Package generated by the BNF Converter.

public class Model extends ModelRule {
  public final ListAutomataRule listautomatarule_;
  public final ListStatementRule liststatementrule_;
  public Model(ListAutomataRule p1, ListStatementRule p2) { listautomatarule_ = p1; liststatementrule_ = p2; }

  public <R,A> R accept(grammar.Absyn.ModelRule.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.Model) {
      grammar.Absyn.Model x = (grammar.Absyn.Model)o;
      return this.listautomatarule_.equals(x.listautomatarule_) && this.liststatementrule_.equals(x.liststatementrule_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listautomatarule_.hashCode())+this.liststatementrule_.hashCode();
  }


}
