package grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class StatementRule implements java.io.Serializable {
  public abstract <R,A> R accept(StatementRule.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammar.Absyn.CheckingStatement p, A arg);
    public R visit(grammar.Absyn.ActionStatement p, A arg);

  }

}
