package grammar.Absyn; // Java Package generated by the BNF Converter.

public class UniversalChecking extends CheckingStatementRule {
  public final String ident_;
  public UniversalChecking(String p1) { ident_ = p1; }

  public <R,A> R accept(grammar.Absyn.CheckingStatementRule.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.UniversalChecking) {
      grammar.Absyn.UniversalChecking x = (grammar.Absyn.UniversalChecking)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
